services:
  nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - '8000:8000' # 호스트:컨테이너
    environment:
      - NODE_ENV=production
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped
